freebsd_instance:
  image_family: freebsd-14-0-snap
task:
  name: FreeBSD
  env:
    matrix:
      # - JULIA_VERSION: 1.6
      - JULIA_VERSION: 1
      # - JULIA_VERSION: nightly
  install_script:
    - sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov coveralls
